# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulator_title', models.CharField(max_length=300)),
            ],
        ),
    ]
